# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 350)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 481, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirmPushButton = QtWidgets.QPushButton(Dialog)
        self.confirmPushButton.setGeometry(QtCore.QRect(430, 300, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirmPushButton.setFont(font)
        self.confirmPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 210, 101, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.timeoutSpinBox = QtWidgets.QSpinBox(Dialog)
        self.timeoutSpinBox.setGeometry(QtCore.QRect(20, 240, 71, 30))
        self.timeoutSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeoutSpinBox.setFont(font)
        self.timeoutSpinBox.setMinimum(5)
        self.timeoutSpinBox.setMaximum(300)
        self.timeoutSpinBox.setObjectName("timeoutSpinBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confirmPushButton.setText(_translate("Dialog", "确定"))
        self.label.setText(_translate("Dialog", "下载超时时间(s)"))
