# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 200)
        self.listLabel = QtWidgets.QLabel(Form)
        self.listLabel.setGeometry(QtCore.QRect(10, 10, 391, 30))
        self.listLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listLabel.setFont(font)
        self.listLabel.setText("")
        self.listLabel.setObjectName("listLabel")
        self.editPushButton = QtWidgets.QPushButton(Form)
        self.editPushButton.setGeometry(QtCore.QRect(420, 80, 71, 30))
        self.editPushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editPushButton.setFont(font)
        self.editPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editPushButton.setObjectName("editPushButton")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 391, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.deletePushButton = QtWidgets.QPushButton(Form)
        self.deletePushButton.setGeometry(QtCore.QRect(420, 120, 71, 30))
        self.deletePushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deletePushButton.setFont(font)
        self.deletePushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deletePushButton.setObjectName("deletePushButton")
        self.addPushButton = QtWidgets.QPushButton(Form)
        self.addPushButton.setGeometry(QtCore.QRect(420, 40, 71, 30))
        self.addPushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addPushButton.setFont(font)
        self.addPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addPushButton.setObjectName("addPushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.editPushButton.setText(_translate("Form", "编辑"))
        self.deletePushButton.setText(_translate("Form", "删除"))
        self.addPushButton.setText(_translate("Form", "新增"))
