# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 540)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 481, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirmPushButton = QtWidgets.QPushButton(Dialog)
        self.confirmPushButton.setGeometry(QtCore.QRect(430, 490, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirmPushButton.setFont(font)
        self.confirmPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.paramsMatchGroupBox = QtWidgets.QGroupBox(Dialog)
        self.paramsMatchGroupBox.setGeometry(QtCore.QRect(20, 440, 281, 41))
        self.paramsMatchGroupBox.setTitle("")
        self.paramsMatchGroupBox.setObjectName("paramsMatchGroupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.paramsMatchGroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 261, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.paramsSimpleMatchRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.paramsSimpleMatchRadioButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.paramsSimpleMatchRadioButton.setFont(font)
        self.paramsSimpleMatchRadioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paramsSimpleMatchRadioButton.setToolTip("")
        self.paramsSimpleMatchRadioButton.setObjectName("paramsSimpleMatchRadioButton")
        self.horizontalLayout.addWidget(self.paramsSimpleMatchRadioButton)
        self.paramsExactMatchRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.paramsExactMatchRadioButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.paramsExactMatchRadioButton.setFont(font)
        self.paramsExactMatchRadioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paramsExactMatchRadioButton.setObjectName("paramsExactMatchRadioButton")
        self.horizontalLayout.addWidget(self.paramsExactMatchRadioButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 410, 81, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confirmPushButton.setText(_translate("Dialog", "确定"))
        self.paramsSimpleMatchRadioButton.setText(_translate("Dialog", "Params简易匹配"))
        self.paramsExactMatchRadioButton.setText(_translate("Dialog", "Params精确匹配"))
        self.label.setText(_translate("Dialog", "匹配模式"))
