# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 279)
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        self.addPushButton = QtWidgets.QPushButton(Dialog)
        self.addPushButton.setGeometry(QtCore.QRect(470, 110, 91, 30))
        self.addPushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addPushButton.setFont(font)
        self.addPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addPushButton.setObjectName("addPushButton")
        self.deletePushButton = QtWidgets.QPushButton(Dialog)
        self.deletePushButton.setGeometry(QtCore.QRect(470, 150, 91, 30))
        self.deletePushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deletePushButton.setFont(font)
        self.deletePushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deletePushButton.setObjectName("deletePushButton")
        self.outputPushButton = QtWidgets.QPushButton(Dialog)
        self.outputPushButton.setGeometry(QtCore.QRect(470, 190, 91, 30))
        self.outputPushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.outputPushButton.setFont(font)
        self.outputPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.outputPushButton.setObjectName("outputPushButton")
        self.downloadLogListWidget = QtWidgets.QListWidget(Dialog)
        self.downloadLogListWidget.setGeometry(QtCore.QRect(20, 70, 431, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.downloadLogListWidget.setFont(font)
        self.downloadLogListWidget.setObjectName("downloadLogListWidget")
        self.clearPushButton = QtWidgets.QPushButton(Dialog)
        self.clearPushButton.setGeometry(QtCore.QRect(470, 70, 91, 31))
        self.clearPushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearPushButton.setFont(font)
        self.clearPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearPushButton.setObjectName("clearPushButton")
        self.browsePushButton = QtWidgets.QPushButton(Dialog)
        self.browsePushButton.setGeometry(QtCore.QRect(470, 20, 89, 30))
        self.browsePushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browsePushButton.setFont(font)
        self.browsePushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browsePushButton.setObjectName("browsePushButton")
        self.browseLineEdit = QtWidgets.QLineEdit(Dialog)
        self.browseLineEdit.setEnabled(False)
        self.browseLineEdit.setGeometry(QtCore.QRect(78, 20, 371, 30))
        self.browseLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseLineEdit.setFont(font)
        self.browseLineEdit.setReadOnly(False)
        self.browseLineEdit.setObjectName("browseLineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 25, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addPushButton.setText(_translate("Dialog", "添加"))
        self.deletePushButton.setText(_translate("Dialog", "删除"))
        self.outputPushButton.setText(_translate("Dialog", "导出"))
        self.clearPushButton.setText(_translate("Dialog", "清空"))
        self.browsePushButton.setText(_translate("Dialog", "浏览"))
        self.label.setText(_translate("Dialog", "导出到："))
