# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 389)
        self.addPushButton = QtWidgets.QPushButton(Dialog)
        self.addPushButton.setGeometry(QtCore.QRect(500, 20, 91, 40))
        self.addPushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPushButton.setFont(font)
        self.addPushButton.setObjectName("addPushButton")
        self.deletePushButton = QtWidgets.QPushButton(Dialog)
        self.deletePushButton.setGeometry(QtCore.QRect(500, 70, 91, 40))
        self.deletePushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deletePushButton.setFont(font)
        self.deletePushButton.setObjectName("deletePushButton")
        self.outputPushButton = QtWidgets.QPushButton(Dialog)
        self.outputPushButton.setGeometry(QtCore.QRect(500, 120, 91, 40))
        self.outputPushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputPushButton.setFont(font)
        self.outputPushButton.setObjectName("outputPushButton")
        self.downloadLogListWidget = QtWidgets.QListWidget(Dialog)
        self.downloadLogListWidget.setGeometry(QtCore.QRect(20, 20, 461, 351))
        self.downloadLogListWidget.setObjectName("downloadLogListWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addPushButton.setText(_translate("Dialog", "添加"))
        self.deletePushButton.setText(_translate("Dialog", "删除"))
        self.outputPushButton.setText(_translate("Dialog", "导出"))
